Public with Sharing class Mapfunction 
{
    Map<Integer ,String> map1 = new Map<Integer,String>(); // Creating Map Key:-Integer And values:-String
  /*  for(Integer i=0;i<=15;i++)        // Insert values In map by using for Loop
    {
        map1.put(i,'Rahul'+i);       // Put Values in map
    }
    System.debug('hello-Map1'+map1);
     System.debug('Hello-map2'+map2);         // copyMenthod  Map1 to Map2 
     
     map<Integer,String> map2 = new map<Integer,String>(map1);// The map elements of m2 are copied from m1

     // to clean Map
       map1.clean();
    // find the value of map one by one using key
    
   
     Map<Id,String> MapAcc = new Map<Id,String>();
    for(Contact a : [Select Id,Name From Contact])
    {
        MapAcc.put(a.Id,a.Name );
    }
    for (id key : MapAcc.keyset())  
   {  
        String Value2 = MapAcc.get(key);
        System.debug('Value2'+Value2);
   }
   */
}